#!/bin/bash
rm /usr/local/etc/php/conf.d/*

cp /usr/local/etc/php/php-production.ini /usr/local/etc/php/php.ini

IFS=';;;;'
envs=(`cat /proc/1/environ | xargs -0 -n 1 echo ';;;;'`)
unset IFS

cd /usr/local/etc/php/conf.d
for _curVar in "${envs[@]}"
do
    value=`echo "$_curVar" | awk -F = '{print $2}'`
    name=`echo "$_curVar" | awk -F = '{print $1}' | xargs`
    if [ "$name" == "" ]
    then
      continue
    fi
    if [ "$name" == "PHP_MODULES" ]
    then
      for MODULE in $value; do
        cp /root/conf.d/docker-php-ext-$MODULE.ini .
      done
    fi
done

if [ -x /init ]; then
  /init
fi
