#!/bin/bash

export PHP_INI_DIR=/usr/local/etc/

composer selfupdate

chmod 775 -R /var/www
chown www-data:www-data -R /var/www
echo "Applying"

# Function to update the fpm configuration to make the service environment variables available
function setEnvironmentVariable() {
 
    if [ -z "$2" ]; then
        return
    fi
 
    echo "Set $1 to $2"

    # Check whether variable already exists
    if grep -q "^env\[$1\]" $PHP_INI_DIR/php-fpm.d/www.conf; then
        # Reset variable
        sed -i "s~^env\[$1.*~env[$1] = \"$2\"~g" $PHP_INI_DIR/php-fpm.d/www.conf
    else
        # Add variable
        echo "env[$1] = \"$2\"" >> $PHP_INI_DIR/php-fpm.d/www.conf
    fi
}

IFS=';;;;'
envs=(`cat /proc/1/environ | xargs -0 -n 1 echo ';;;;'`)
unset IFS

echo ${envs[@]}

rm /etc/ssmtp/ssmtp.conf

for _curVar in "${envs[@]}"
do
    value=`echo "$_curVar" | awk -F= '{print $2}'`
    name=`echo "$_curVar" | awk -F= '{print $1}' | xargs`
    if [ "$name" == "" ]
    then
      continue
    fi

    if [ "$name" == "DEVUSER" ]
    then
      DEVUSER=$value
    fi

    if [ "$name" == "TIMEZONE" ]
    then
      sed -i -e "s~;date.timezone\s*=.*~date.timezone=$value~g" /usr/local/etc/php/php.ini
    fi

    if [[ $name == SSMTP_* ]]
    then
      echo "`echo $name | cut -d'_' -f 2`=$value" >>/etc/ssmtp/ssmtp.conf
      continue
    fi


    # awk has split them by the equals sign
    # Pass the name and value to our function
    setEnvironmentVariable "$name" "$value"
done

#-fpm configuration
sed -i -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g" /usr/local/etc/php/php.ini
sed -i -e "s/upload_max_filesize\s*=\s*2M/upload_max_filesize = 100M/g" /usr/local/etc/php/php.ini
sed -i -e "s/post_max_size\s*=\s*8M/post_max_size = 100M/g" /usr/local/etc/php/php.ini
sed -i -e "s/short_open_tag\s*=\s*Off/short_open_tag = On/g" /usr/local/etc/php/php.ini

sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" /usr/local/etc/php-fpm.conf

sed -i -e "s/user\s*=.*/user = $DEVUSER/g" /usr/local/etc/php-fpm.d/www.conf

sed -i -e "s/;catch_workers_output\s*=\s*yes/catch_workers_output = yes/g" /usr/local/etc/php-fpm.d/www.conf

#find /usr/local/etc/php/cli/conf.d/ -name "*.ini" -exec sed -i -re 's/^(\s*)#(.*)/\1;\2/g' {} \;
